[project]
name = "phonetic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sounddevice",
    "soundfile",
    "numpy",
    "pynput; sys_platform != 'linux'",
    "python-xlib; sys_platform == 'linux'",
    "pyperclip",
    "python-dotenv",
    "httpx",
]

[project.scripts]
phonetic = "main:main"

[tool.simple_whisper]
# Path to project working directory when running as a service
working_directory = "/home/eksno/vcs/startino/phonetic"
